name: Build docker image and create release
on:
  push:
    tags:
      - "*.*"
env:
  REGISTRY_PROJECT: rickarts
  REGISTRY_NAME: now-playing

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          makeLatest: true
          bodyFile: "CHANGELOG-RELEASE.md"
          skipIfReleaseExists: true
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout directory
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin ${{ secrets.REGISTRY_URL }}
          docker build . --file Dockerfile -t ${{ secrets.REGISTRY_URL }}/${{env.REGISTRY_PROJECT}}/${{env.REGISTRY_NAME}}
      - name: Tag the Docker image
        run: |
          docker tag ${{ secrets.REGISTRY_URL }}/${{env.REGISTRY_PROJECT}}/${{env.REGISTRY_NAME}} ${{ secrets.REGISTRY_URL }}/${{env.REGISTRY_PROJECT}}/${{env.REGISTRY_NAME}}:${{github.ref_name}}
      - name: Push the images
        run: docker push --all-tags ${{ secrets.REGISTRY_URL }}/${{env.REGISTRY_PROJECT}}/${{env.REGISTRY_NAME}}
